---
- name: 'Including {{ ansible_os_family }} spefic playbooks'
  include: '{{ ansible_os_family }}.yml'

- name: Provision from OS repositories
  package:
    name: python-pip, httpd, mod_ssl, python-certbot-apache, links
    state: present

- name: Provision from PIP repositories
  pip:
    name: pexpect
    state: present

- name: Services are running and starts after reboot
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  with_items:
    - httpd

- name: Restarting services
  service:
    name: '{{ item }}'
    state: restarted
  with_items:
    - httpd

- name: Running Certbot
  expect:
    command: 'certbot --apache certonly'
    responses:
      (?i)select: '1,2'
      (?i)email: 'webarchiv@nkp.cz'
      (?i)gree: 'A'
      (?i)es: 'Y'
