---
- hosts: all
  tasks:
#   - name: 3_Copying virtual.conf.
#     copy: src="/home/lindon/VMasinky/subory/virtual.conf" dest="/etc/nginx/conf.d/virtual.conf"
   - name: 3_Copying Skuska.cz.
     copy: src="/home/lindon/VMasinky/subory2/skuska.cz" dest="/var/www/"  owner=apache group=apache mode=0755
#   - name: 4_Setting up Virtual hosts dir available
#     file: path="/etc/httpd/sites-available" state="directory" mode="0755"
#   - name: 4_Setting up Virtual hosts dir enabled
#     file: path="/etc/httpd/sites-enabled" state="directory" mode="0755"
#   - name: 4_Copying httpd.conf.
#     copy: src="/home/lindon/VMasinky/subory2/httpd.conf" dest="/etc/httpd/conf/httpd.conf"
   - name: 4_Copying to skuska.cz.conf.
     copy: src="/home/lindon/VMasinky/subory2/skuska.cz.conf" dest="/etc/httpd/conf.d/skuska.cz.conf"
#   - name: Creating symbolic links in between
#     file: src="/etc/httpd/sites-available/skuska.cz.conf" dest="/etc/httpd/sites-enabled/skuska.cz.conf" owner=apache group=apache state=link
   - name: 4_Storing etc/hosts for VirtualHosts purposes.
     copy: src="/home/lindon/VMasinky/subory2/hosts" dest="/etc/hosts"
#       -w /var/www/skuska.cz -d skuska.cz -d www.skuska.cz'
